# Generated by Django 3.2.2 on 2021-06-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to='profileImg'),
        ),
    ]
